#!/usr/bin/env bash
# ****************************************************
#
#   Setup - Homebrew
#
# ****************************************************

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Bash & Bash Completion
brew install bash
brew install bash-completion

# Install font tools.
brew tap bramstein/webfonttools
brew install sfnt2woff
brew install sfnt2woff-zopfli
brew install woff2

# Git
brew install git
brew install git-lfs

# webkit2png
# -> Command-line webpage screenshots
brew install webkit2png

# Install more recent versions of some OS X tools.
brew install vim --override-system-vi

# Install node
brew install node

# Install watchman
brew install watchman

# Install other useful binaries.
brew install imagemagick --with-webp

# Remove outdated versions from the cellar
brew cleanup
