#!/usr/bin/env bash
# ****************************************************
#
#   Setup - NPM
#
# ****************************************************

packages=(
  bower
  browser-sync
  grunt
  grunt-cli
  imageoptim-cli
  stylestats
  svgo
  yo
  gulp
  brunch
  ember-cli
  jshint
)

for package in ${packages[@]}; do
  npm install -g $package
done
